[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project]
dependencies = [ "authlib", "Flask", "simplematrixbotlib" ]
name = "timecarder"
requires-python = ">=3.10"

[project.scripts]
timecardbot = 'bot:main'

[tool.poetry]
name = "timecarder"
version = "0.1.0"
description = ""
authors = ["Benjamin Sperry <benjamin@gleipnir.technology>", "Eli Ribble <eli@gliepnir.technology"]
# license = "BSD"
packages = [
  { include = "timecarder" }
]

[tool.poetry.dependencies]
python = "^3.10"

